"use client";

import Callout, {
  CodeBlock,
  InlineCode,
  SectionDivider,
  Step,
} from "@/components/docs/DocsComponents";
import Link from "next/link";

export default function DocsOtherLLMs() {
  return (
    <article className="docs-prose w-full max-w-3xl">

      {/* ── Page badge ───────────────────────────────────────────── */}
      <div className="mb-3 flex items-center gap-2">
        <span className="rounded-full border border-neon-purple/30 bg-neon-purple/10 px-3 py-0.5 text-xs font-semibold text-neon-purple-light">
          Platform Guides
        </span>
        <span className="text-slate-700">/</span>
        <span className="text-xs text-slate-500">Other LLMs</span>
      </div>

      {/* ── H1 ───────────────────────────────────────────────────── */}
      <h1 id="other-llms" className="scroll-mt-24">
        Using Custom Instructions with Other LLMs
      </h1>

      <p>
        The Master Custom Instruction generated by this tool is built on{" "}
        <strong>universal standards</strong> — plain Markdown formatting and
        structured{" "}
        <InlineCode>{`<xml>`}</InlineCode>-style tags. This makes it{" "}
        <strong>fully portable</strong> across any LLM that accepts a system
        prompt, whether it&apos;s a commercial API, a locally hosted open-source
        model, or a chat interface.
      </p>
      <p>
        Models like <strong>Meta Llama 3</strong>, <strong>Mistral</strong>,{" "}
        <strong>Qwen</strong>, and <strong>DeepSeek</strong> respond particularly
        well to structured system instructions because they were fine-tuned on
        data that includes Markdown and XML-annotated reasoning chains — the
        exact format our generator produces.
      </p>

      <Callout variant="tip" title="Universal Compatibility">
        <p>
          You don&apos;t need to modify your generated instruction to use it with
          a different model. The{" "}
          <InlineCode>{`<self_reflection>`}</InlineCode> tags in Section 3 (The
          Cognitive Loop) are interpreted as internal reasoning directives by
          virtually all modern instruction-tuned models.
        </p>
      </Callout>

      <SectionDivider />

      {/* ── LOCAL ENVIRONMENTS ───────────────────────────────────── */}
      <section id="local-environments" className="scroll-mt-24">
        <h2>Local Environments (LM Studio &amp; Ollama)</h2>
        <p>
          Local inference tools like{" "}
          <a
            href="https://lmstudio.ai"
            target="_blank"
            rel="noopener noreferrer"
            className="text-neon-cyan"
          >
            LM Studio
          </a>{" "}
          and{" "}
          <a
            href="https://ollama.com"
            target="_blank"
            rel="noopener noreferrer"
            className="text-neon-cyan"
          >
            Ollama
          </a>{" "}
          both expose a <strong>System Prompt</strong> configuration field.
          Simply paste your generated Master Instruction directly into this
          field and it will be prepended to every conversation automatically.
        </p>

        <h3 id="lm-studio" className="scroll-mt-24">LM Studio</h3>
        <div className="space-y-3 my-5">
          <Step number={1} title="Open the Chat panel">
            Launch LM Studio and load your preferred model from the local model
            library. Navigate to the <InlineCode>Chat</InlineCode> tab on the
            left rail.
          </Step>
          <Step number={2} title='Find the "System Prompt" field'>
            In the right-hand configuration panel, locate the{" "}
            <InlineCode>System Prompt</InlineCode> text area near the top. It
            may be collapsed — click to expand it.
          </Step>
          <Step number={3} title="Paste your Master Instruction">
            Copy your generated instruction from the Output Studio and paste it
            into the System Prompt field. LM Studio will persist this across the
            entire session.
          </Step>
          <Step number={4} title="Start chatting">
            Begin your conversation. The model will now operate entirely within
            the persona, mission, and constraints you defined.
          </Step>
        </div>

        <Callout variant="note">
          <p>
            In LM Studio, you can save a configured session as a{" "}
            <strong>Preset</strong> so you don&apos;t need to re-paste the
            instruction every time. Click{" "}
            <InlineCode>Save Preset</InlineCode> in the top-right corner after
            configuring your system prompt.
          </p>
        </Callout>

        <h3 id="ollama" className="scroll-mt-24 mt-8">Ollama (Modelfile)</h3>
        <p>
          With Ollama, you can bake the system instruction directly into a
          custom <strong>Modelfile</strong> — creating a named, reusable model
          variant with your instruction pre-loaded.
        </p>

        <CodeBlock language="modelfile" filename="Modelfile">
{`FROM llama3

# Paste your Master Custom Instruction below:
SYSTEM """
# 🎭 1. Role & Identity
Assume the role of a Senior TypeScript Engineer...

# 🎯 2. Mission & Objective
Your mission is to review, optimize, and generate production-ready...

# 🧠 3. The Cognitive Loop (Internal Reflection)
Before answering, you MUST use <self_reflection> tags to think internally...

[... rest of your generated instruction ...]
"""`}
        </CodeBlock>

        <div className="space-y-3 my-5">
          <Step number={1} title="Create the Modelfile">
            Save the snippet above as a file named{" "}
            <InlineCode>Modelfile</InlineCode> in any directory.
          </Step>
          <Step number={2} title="Build the custom model">
            <span>
              Run{" "}
              <InlineCode>ollama create my-expert -f ./Modelfile</InlineCode> in
              your terminal. Ollama will create a new model entry named{" "}
              <InlineCode>my-expert</InlineCode>.
            </span>
          </Step>
          <Step number={3} title="Run your expert model">
            <span>
              Call it with{" "}
              <InlineCode>ollama run my-expert</InlineCode>. Your custom
              instruction is now permanently baked in.
            </span>
          </Step>
        </div>

        <Callout variant="warning">
          <p>
            Ollama Modelfiles use triple-quoted strings. If your Master
            Instruction contains triple quotes (<InlineCode>{`"""`}</InlineCode>
            ), escape them as <InlineCode>{`\\"""`}</InlineCode> to avoid
            breaking the Modelfile syntax.
          </p>
        </Callout>
      </section>

      <SectionDivider />

      {/* ── API INTEGRATION ──────────────────────────────────────── */}
      <section id="api-integration" className="scroll-mt-24">
        <h2>API Integration</h2>
        <p>
          For developers calling LLM APIs directly — whether that&apos;s{" "}
          <strong>OpenAI</strong>, <strong>DeepSeek</strong>,{" "}
          <strong>Groq</strong>, <strong>Together AI</strong>, or any
          OpenAI-compatible endpoint — inject the Master Instruction as the
          first message in the <InlineCode>messages</InlineCode> array with the
          role set to <InlineCode>system</InlineCode>.
        </p>

        <h3 id="messages-format" className="scroll-mt-24">
          The Messages Format
        </h3>
        <p>
          All major LLM APIs follow the same{" "}
          <strong>Chat Completion</strong> message format. The{" "}
          <InlineCode>system</InlineCode> role is the highest-priority context
          layer — the model reads it before anything the user says.
        </p>

        <CodeBlock language="json" filename="POST /v1/chat/completions">
{`{
  "model": "deepseek-chat",
  "temperature": 0.3,
  "messages": [
    {
      "role": "system",
      "content": "# 🎭 1. Role & Identity\\nAssume the role of a Senior TypeScript Engineer holding a PhD in Computer Science...\\n\\n# 🎯 2. Mission & Objective\\nYour mission is to review, optimize, and generate production-ready TypeScript code...\\n\\n# 🧠 3. The Cognitive Loop (Internal Reflection)\\nBefore answering, you MUST use <self_reflection> tags to think internally:\\n1. Create a 5-point evaluation rubric...\\n\\n[... sections 4-6 ...]"
    },
    {
      "role": "user",
      "content": "Review this function for performance issues and security vulnerabilities."
    }
  ]
}`}
        </CodeBlock>

        <Callout variant="important" title="Temperature Setting">
          <p>
            Set <InlineCode>temperature</InlineCode> to{" "}
            <InlineCode>0.2</InlineCode>–<InlineCode>0.4</InlineCode> when
            using structured Custom Instructions. Higher temperatures cause the
            model to drift from the persona and format rules defined in your
            instruction. Our backend enforces <InlineCode>0.3</InlineCode> by
            default for this reason.
          </p>
        </Callout>

        <h3 id="python-example" className="scroll-mt-24 mt-8">
          Python Example
        </h3>
        <p>
          The snippet below works with any OpenAI-compatible SDK — just swap
          the <InlineCode>base_url</InlineCode> and{" "}
          <InlineCode>api_key</InlineCode> for your provider.
        </p>

        <CodeBlock language="python" filename="example_integration.py">
{`import openai

# Load your Master Instruction (from the Output Studio copy)
MASTER_INSTRUCTION = """
# 🎭 1. Role & Identity
Assume the role of a Senior TypeScript Engineer...
[... your full generated instruction ...]
"""

client = openai.OpenAI(
    base_url="https://api.deepseek.com",  # or api.groq.com, etc.
    api_key="your-api-key",
)

response = client.chat.completions.create(
    model="deepseek-chat",
    temperature=0.3,
    messages=[
        {"role": "system", "content": MASTER_INSTRUCTION},
        {"role": "user",   "content": "Review this React component for issues."},
    ],
)

print(response.choices[0].message.content)`}
        </CodeBlock>

        <h3 id="compatible-providers" className="scroll-mt-24 mt-8">
          Compatible Providers
        </h3>
        <p>
          The following providers all support the{" "}
          <InlineCode>system</InlineCode> role in their Chat Completions API and
          are fully compatible with your generated instruction:
        </p>

        <div className="my-5 grid grid-cols-1 gap-3 sm:grid-cols-2">
          {[
            { name: "OpenAI", tag: "GPT-4o, o3", color: "border-emerald-500/20 bg-emerald-500/[0.03]" },
            { name: "DeepSeek", tag: "deepseek-chat, R1", color: "border-neon-cyan/20 bg-neon-cyan/[0.03]" },
            { name: "Groq", tag: "Llama 3, Mixtral", color: "border-neon-purple/20 bg-neon-purple/[0.03]" },
            { name: "Together AI", tag: "200+ open models", color: "border-amber-500/20 bg-amber-500/[0.03]" },
            { name: "Anthropic", tag: "Claude 3.5 Sonnet", color: "border-rose-500/20 bg-rose-500/[0.03]" },
            { name: "Google", tag: "Gemini 2.0 Flash", color: "border-sky-500/20 bg-sky-500/[0.03]" },
          ].map((p) => (
            <div
              key={p.name}
              className={`rounded-lg border p-4 transition-colors duration-150 hover:border-white/10 ${p.color}`}
            >
              <p className="font-semibold text-slate-200">{p.name}</p>
              <p className="mt-0.5 text-xs text-slate-500">{p.tag}</p>
            </div>
          ))}
        </div>

        {/* Next page nav */}
        <div className="mt-12 rounded-xl border border-white/[0.07] bg-white/[0.02] p-5">
          <p className="text-xs uppercase tracking-wider text-slate-600 mb-1">Next</p>
          <Link
            href="/docs?page=prompt-chaining"
            className="font-semibold text-white hover:text-neon-cyan transition-colors"
          >
            Advanced — Prompt Chaining →
          </Link>
        </div>
      </section>
    </article>
  );
}
