import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | Orxis",
  description:
    "The terms governing your use of the Orxis AI instruction generator.",
};

// ── Shared prose helpers (mirrored from privacy/page.tsx) ─────────────

function SectionHeading({ children }: { children: React.ReactNode }) {
  return (
    <h2 className="mt-12 mb-4 text-[17px] font-semibold text-white border-b border-white/[0.07] pb-2">
      {children}
    </h2>
  );
}

function Body({ children }: { children: React.ReactNode }) {
  return (
    <p className="text-[14.5px] leading-[1.9] text-slate-400 mt-3">
      {children}
    </p>
  );
}

function BulletList({ items }: { items: string[] }) {
  return (
    <ul className="mt-3 ml-5 list-disc space-y-2">
      {items.map((item) => (
        <li key={item} className="text-[14.5px] leading-[1.8] text-slate-400">
          {item}
        </li>
      ))}
    </ul>
  );
}

// ── Page ─────────────────────────────────────────────────────────────────

export default function TermsPage() {
  return (
    <article>

      {/* Header */}
      <div className="mb-10">
        <p className="mb-3 text-[10.5px] font-bold uppercase tracking-[0.16em] text-slate-600">
          Legal
        </p>
        <h1 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
          Terms of Service
        </h1>
        <p className="mt-3 text-[13px] text-slate-600">
          Last Updated: <span className="text-slate-500">July 12, 2026</span>
        </p>
      </div>

      {/* Intro */}
      <div className="rounded-xl border border-white/[0.06] bg-white/[0.02] px-6 py-5">
        <Body>
          By accessing or using Orxis, you agree to these terms. If you do not
          agree, please do not use the service. These terms are written to be
          clear and practical.
        </Body>
      </div>

      {/* Section 1 */}
      <SectionHeading>1. The Service</SectionHeading>
      <Body>
        Orxis provides a structured AI custom instruction generator. You provide
        information about your desired AI persona, task, tone, and constraints; the
        service returns a structured instruction prompt designed to improve AI
        consistency and adherence.
      </Body>
      <Body>
        The underlying AI model is provided by a third-party API (currently Google
        Gemini). The quality, accuracy, and behaviour of that model are outside our
        control. We are not responsible for outputs produced by the underlying model.
      </Body>

      {/* Section 2 */}
      <SectionHeading>2. Your Responsibilities</SectionHeading>
      <Body>
        You are responsible for how you use the outputs generated by Orxis. The
        prompts produced by this service are tools — their suitability for a given
        task, and the consequences of deploying them, are your determination to make.
      </Body>
      <Body>You agree not to use Orxis to generate instructions for:</Body>
      <BulletList
        items={[
          "Harmful, deceptive, or illegal AI behaviour",
          "Impersonation of real individuals or entities",
          "Generating content that violates applicable laws in your jurisdiction",
          "Circumventing safety measures in AI systems",
        ]}
      />

      {/* Section 3 */}
      <SectionHeading>3. Acceptable Use</SectionHeading>
      <Body>
        Orxis is a free service supported by the community. To ensure fair access
        for everyone, you agree not to:
      </Body>
      <BulletList
        items={[
          "Automate or script mass requests to the generation endpoint",
          "Attempt to circumvent, reverse engineer, or exploit the API infrastructure",
          "Use the service in any way that degrades performance for other users",
          "Submit content to the Community Gallery that infringes third-party rights or violates applicable law",
        ]}
      />
      <Body>
        We reserve the right to block access for users or IP addresses that violate
        these terms, without prior notice.
      </Body>

      {/* Section 4 */}
      <SectionHeading>4. Service Availability</SectionHeading>
      <Body>
        Orxis is hosted on Vercel and depends on third-party infrastructure including
        database and AI API services. We aim for high availability and make
        reasonable efforts to maintain uptime. However, we cannot guarantee
        uninterrupted service. Downtime may occur due to:
      </Body>
      <BulletList
        items={[
          "Scheduled maintenance",
          "Third-party infrastructure outages",
          "Circumstances outside our reasonable control",
        ]}
      />
      <Body>
        We are not liable for any losses or damages caused by service interruption.
      </Body>

      {/* Section 5 */}
      <SectionHeading>5. Intellectual Property</SectionHeading>
      <Body>
        The Orxis application — including its UI design, source code, prompt
        generation framework, and all associated intellectual property — is
        proprietary. The generated prompt text that you produce belongs to you.
        See our{" "}
        <a
          href="/license"
          className="text-blue-400 underline underline-offset-2 hover:text-blue-300"
        >
          License page
        </a>{" "}
        for a full breakdown.
      </Body>

      {/* Section 6 */}
      <SectionHeading>6. Disclaimer of Warranties</SectionHeading>
      <Body>
        Orxis is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without
        warranties of any kind, express or implied, including but not limited to
        warranties of merchantability, fitness for a particular purpose, or
        non-infringement. We do not warrant that the service will be error-free,
        uninterrupted, or that outputs will meet your expectations.
      </Body>

      {/* Section 7 */}
      <SectionHeading>7. Limitation of Liability</SectionHeading>
      <Body>
        To the maximum extent permitted by applicable law, Orxis and its operators
        are not liable for any indirect, incidental, special, consequential, or
        punitive damages arising from your use of — or inability to use — the
        service, even if we have been advised of the possibility of such damages.
      </Body>

      {/* Section 8 */}
      <SectionHeading>8. Governing Law</SectionHeading>
      <Body>
        These terms are governed by and construed in accordance with the laws of
        Thailand, without regard to its conflict of law provisions. Any disputes
        arising from these terms shall be subject to the exclusive jurisdiction of
        the courts of Thailand.
      </Body>

      {/* Section 9 */}
      <SectionHeading>9. Changes to These Terms</SectionHeading>
      <Body>
        We may update these terms from time to time. Changes will be reflected in the
        &ldquo;Last Updated&rdquo; date at the top of this page. Continued use of
        Orxis after changes are posted constitutes your acceptance of the revised
        terms. For significant changes, we will make a reasonable effort to notify
        users through the application.
      </Body>

      {/* Section 10 */}
      <SectionHeading>10. Contact</SectionHeading>
      <Body>
        For legal inquiries, contact us at{" "}
        <a target="_blank" rel="noopener noreferrer" href="mailto:orxis.app@gmail.com"
          className="text-blue-400 underline underline-offset-2 hover:text-blue-300"
        >
          orxis.app@gmail.com
        </a>
        .
      </Body>

      {/* Footer note */}
      <div className="mt-16 border-t border-white/[0.05] pt-8">
        <p className="text-[12.5px] text-slate-700">
          Governed by the laws of Thailand. These terms do not constitute legal advice.
          Consult a qualified legal professional for advice specific to your situation.
        </p>
      </div>

    </article>
  );
}
